default:
  interruptible: true
  artifacts:
    expire_in: 30 days

variables:
  DOCKER_TLS_CERTDIR: "/certs"


.tests:
  stage: test
  image: ubuntu:latest
  coverage: '/TOTAL.*\s+(\d+%)$/'
  rules:
    - changes:
        - dr_emu/**/*
        - tests/**/*
        - parser/**/*
        - cli/**/*
        - alembic/**/*
        - shared/**/*
        - alembic.ini
        - .gitlab-ci.yml
        - poetry.lock
        - pyproject.toml
    - when: never
  before_script:
    - export $(grep -v '^#' .env | xargs)
    - apt-get update
    - apt-get install -y build-essential curl python3-dev g++ gcc git
    - apt install -y pipx
    - pipx ensurepath
    - pipx install poetry
    - pipx ensurepath
    - git clone https://oauth2:$CYST_TOKEN@gitlab.ics.muni.cz/cyst/cyst-core.git
    - export PATH="/root/.local/bin:$PATH"
    - poetry install


unit_tests:
  extends: .tests
  script:
    - poetry run pytest tests/unit/

integration_tests:
  extends: .tests
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - poetry run pytest tests/integration/