version: '3.9'
services:
  dr_emu_db:
    restart: always
    image: postgres:15
    container_name: dr-emu-db
    env_file:
      - .env
    volumes:
      - dr-emu-data:/var/lib/postgresql/data
    healthcheck:
      test: /usr/bin/pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 20s
      timeout: 10s
      retries: 5
    ports:
      - "127.0.0.1:5432:5432"

  dr_emu:
      restart: always
      build:
        context: .
        dockerfile: Dockerfile
        target: dr_emu
        args:
          POETRY_VIRTUALENVS_IN_PROJECT: true
      container_name: dr-emu
      depends_on:
        dr_emu_db:
          condition: service_healthy
      ports:
        - "0.0.0.0:8000:8000"
      env_file:
        - .env
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

volumes:
  dr-emu-data:
