version: '3.9'
services:
  wan_router:
    build:
      context: .
#      args:
#        CONFIG: wan_router.sh
    restart: always
    container_name: wan_router
    privileged: true
    cap_add:
      - NET_ADMIN

#  loki:
#    image: nicolaka/netshoot
#    restart: always
#    container_name: loki
#    privileged: true
#    network_mode: none
##    entrypoint: ["sh", "-c", "ip route add 192.168.92.0/24 via 192.168.90.1 && sleep infinity"]
#    entrypoint: ["sleep", "infinity"]
#    cap_add:
#      - NET_ADMIN
#
#  odin:
#    image: nicolaka/netshoot
#    restart: always
#    container_name: odin
#    network_mode: none
#    cap_add:
#      - NET_ADMIN
##    entrypoint: [ 'sh', '-c', 'ip route del default && ip route add default via 192.168.91.1 && sleep infinity' ]
#    entrypoint: ["sleep", "infinity"]
#
#networks:
#  management:
#    ipam:
#      config:
#        - subnet: 192.168.50.0/24
