version: '3.9'
services:
  r1:
    image: nicolaka/netshoot
    restart: always
    container_name: r1
    privileged: true
    networks:
      dmz:
        ipv4_address: 192.168.90.1
      public:
        ipv4_address: 192.168.92.1
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN

  r2:
    image: nicolaka/netshoot
    restart: always
    container_name: r2
    privileged: true
    networks:
      dmz:
        ipv4_address: 192.168.90.2
      private:
        ipv4_address: 192.168.91.1
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN

  odin:
    image: nicolaka/netshoot
    restart: always
    container_name: odin
    depends_on:
      - r2
    networks:
      private:
        ipv4_address: 192.168.91.5
    cap_add:
      - NET_ADMIN
    command: [ 'sh', '-c', 'ip route del default && ip route add default via 192.168.91.1 && sleep infinity' ]

  loki:
    image: nicolaka/netshoot
    restart: always
    container_name: loki
    depends_on:
      - r1
    networks:
      public:
        ipv4_address: 192.168.92.5
    cap_add:
      - NET_ADMIN
    command: ['sh', '-c', 'ip route del default && ip route add default via 192.168.92.1 && sleep infinity']

volumes:
  cryton_core_db_data:


networks:
  public:
    ipam:
      config:
        - subnet: 192.168.92.0/24
          gateway: 192.168.92.250
  private:
    ipam:
      config:
        - subnet: 192.168.91.0/24
          gateway: 192.168.91.250
  dmz:
    ipam:
      config:
        - subnet: 192.168.90.0/24
          gateway: 192.168.90.250
