version: '3.9'
services:
  wan_router:
    build:
      context: .
      args:
        config: wan_config.sh
    restart: always
    container_name: wan_router
    privileged: true
    networks:
      management:
        ipv4_address: 192.168.50.10
      dmz:
        ipv4_address: 192.168.93.1
      cryton:
        ipv4_address: 192.168.90.1
    volumes:
      - ./router_scripts/wan_router.sh:/home/vyos/config.sh
    cap_add:
      - NET_ADMIN

  user_router:
    build:
      context: .
      args:
        config: user_config.sh
    restart: always
    container_name: user_router
    privileged: true
    networks:
      management:
        ipv4_address: 192.168.50.11
      user_subnet:
        ipv4_address: 192.168.91.1
    volumes:
      - ./router_scripts/user_router.sh:/home/vyos/config.sh
    entrypoint: "/sbin/init"
    command: ["/bin/bash", "-c", "sudo chmod +x /home/vyos/config.sh ; runuser -u vyos -c ./config.sh"]
    cap_add:
      - NET_ADMIN

  server_router:
    build:
      context: .
      args:
        config: server_config.sh
    restart: always
    container_name: server_router
    privileged: true
    networks:
      management:
        ipv4_address: 192.168.50.12
      server_subnet:
        ipv4_address: 192.168.92.1
    volumes:
      - ./router_scripts/server_router.sh:/home/vyos/config.sh
    entrypoint: "/sbin/init"
    command: ["/bin/bash", "-c", "sudo chmod +x /home/vyos/config.sh && runuser -l vyos -c ./config.sh"]
    cap_add:
      - NET_ADMIN

  loki:
    image: nicolaka/netshoot
    restart: always
    container_name: loki
    privileged: true
    networks:
      server_subnet:
        ipv4_address: 192.168.92.40
    cap_add:
      - NET_ADMIN
    command: [ 'sh', '-c', 'ip route del default && ip route add default via 192.168.92.1 && sleep infinity' ]

  thor:
    image: nicolaka/netshoot
    restart: always
    container_name: thor
    privileged: true
    networks:
      cryton:
        ipv4_address: 192.168.90.40
    cap_add:
      - NET_ADMIN
    command: [ 'sh', '-c', 'ip route del default && ip route add default via 192.168.90.1 && sleep infinity' ]

  odin:
    image: nicolaka/netshoot
    restart: always
    container_name: odin
    privileged: true
    networks:
      user_subnet:
        ipv4_address: 192.168.91.40
    cap_add:
      - NET_ADMIN
    command: [ 'sh', '-c', 'ip route del default && ip route add default via 192.168.91.1 && sleep infinity' ]

  heimdal:
    image: nicolaka/netshoot
    restart: always
    container_name: heimdal
    privileged: true
    networks:
      dmz:
        ipv4_address: 192.168.93.40
    cap_add:
      - NET_ADMIN
    command: [ 'sh', '-c', 'ip route del default && ip route add default via 192.168.93.1 && sleep infinity' ]

networks:
  cryton:
    ipam:
      config:
        - subnet: 192.168.90.0/24
          gateway: 192.168.90.250
  user_subnet:
    ipam:
      config:
        - subnet: 192.168.91.0/24
          gateway: 192.168.91.250
  server_subnet:
    ipam:
      config:
        - subnet: 192.168.92.0/24
          gateway: 192.168.92.250
  dmz:
    ipam:
      config:
        - subnet: 192.168.93.0/24
          gateway: 192.168.93.250
  management:
    ipam:
      config:
        - subnet: 192.168.50.0/24
          gateway: 192.168.50.250

