version: '3.9'
services:
  router:
    image: registry.gitlab.ics.muni.cz:443/244656/ai-dojo-docker-testbed:vyos-1.4
    restart: always
    container_name: router
    privileged: true
    networks:
      dmz:
        ipv4_address: 192.168.50.1
      cryton:
        ipv4_address: 192.168.91.1
      asgard:
        ipv4_address: 192.168.90.1
      nilfheim:
        ipv4_address: 192.168.92.1
    entrypoint: "/sbin/init"
    cap_add:
      - NET_ADMIN

  cryton_core:
    restart: always
    image: registry.gitlab.ics.muni.cz:443/cryton/cryton-core:latest
    container_name: cryton-core
    ports:
      - "8000:80"
    depends_on:
      cryton_pgbouncer:
        condition: service_healthy
      cryton_rabbit:
        condition: service_healthy
    networks:
      cryton:
        ipv4_address: 192.168.91.21


  cryton_proxy:
    restart: always
    image: registry.gitlab.ics.muni.cz:443/cryton/cryton-core:proxy-latest
    container_name: cryton-proxy
    network_mode: service:cryton_core
    depends_on:
      cryton_core:
        condition: service_started
    networks:
      cryton:
        ipv4_address: 192.168.91.22

  cryton_db:
    restart: always
    image: postgres:13
    container_name: cryton-db
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: $CRYTON_CORE_DB_PASSWORD
      POSTGRES_USER: $CRYTON_CORE_DB_USERNAME
      POSTGRES_DB: $CRYTON_CORE_DB_NAME
    volumes:
      - cryton_core_db_data:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      cryton:
        ipv4_address: 192.168.91.23

  cryton_pgbouncer:
    restart: always
    image: edoburu/pgbouncer:1.18.0
    container_name: cryton-pgbouncer
    depends_on:
      cryton_db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DB_HOST: cryton_db
      DB_USER: $CRYTON_CORE_DB_USERNAME
      DB_NAME: $CRYTON_CORE_DB_NAME
      DB_PASSWORD: $CRYTON_CORE_DB_PASSWORD
      MAX_CLIENT_CONN: 5000
      DEFAULT_POOL_SIZE: 8
      MIN_POOL_SIZE: 8
      POOL_MODE: transaction
    expose:
      - "5432"
    healthcheck:
      test: /usr/bin/pg_isready -h 0.0.0.0 -p 5432
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      cryton:
        ipv4_address: 192.168.91.20


  cryton_rabbit:
    restart: always
    image: rabbitmq:3.11-management
    container_name: cryton-rabbit
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: $CRYTON_CORE_RABBIT_USERNAME
      RABBITMQ_DEFAULT_PASS: $CRYTON_CORE_RABBIT_PASSWORD
    ports:
      - "5672:5672"
      - "127.0.0.1:15672:15672"
    healthcheck:
      test: rabbitmqctl eval '
        { true, rabbit_app_booted_and_running } = { rabbit:is_booted(node()), rabbit_app_booted_and_running },
        { [], no_alarms } = { rabbit:alarms(), no_alarms },
        [] /= rabbit_networking:active_listeners(),
        rabbitmq_node_is_healthy.
        ' || exit 1
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      cryton:
        ipv4_address: 192.168.91.24


  cryton_worker:
    restart: always
    image: registry.gitlab.ics.muni.cz:443/cryton/cryton-worker:kali-latest
    container_name: cryton-worker
    depends_on:
      router:
        condition: service_started
      cryton_rabbit:
        condition: service_healthy
    environment:
      CRYTON_WORKER_NAME: attacker
      CRYTON_WORKER_DEBUG: true
      CRYTON_WORKER_MODULES_DIR: /app/cryton-modules/modules
      CRYTON_WORKER_INSTALL_REQUIREMENTS: true
      CRYTON_WORKER_MSFRPCD_HOST: localhost
      CRYTON_WORKER_MSFRPCD_USERNAME: msf
      CRYTON_WORKER_MSFRPCD_PASSWORD: toor
      CRYTON_WORKER_RABBIT_HOST: cryton_rabbit
      CRYTON_WORKER_RABBIT_PORT: 5672
      CRYTON_WORKER_RABBIT_USERNAME: cryton
      CRYTON_WORKER_RABBIT_PASSWORD: cryton
      CRYTON_WORKER_EMPIRE_HOST: empire
      CRYTON_WORKER_EMPIRE_PORT: 1337
      CRYTON_WORKER_EMPIRE_USERNAME: empireadmin
      CRYTON_WORKER_EMPIRE_PASSWORD: password123
    entrypoint: [ "sh", "-c", "msfrpcd -P toor && cryton-worker start" ]
    command: ['sh', '-c', 'ip route del default && ip route add default via 192.168.91.1']
    networks:
      cryton:
        ipv4_address: 192.168.91.30

  thor:
    image: nicolaka/netshoot
    restart: always
    depends_on:
      - router
    container_name: thor
    networks:
      asgard:
        ipv4_address: 192.168.90.3
    cap_add:
      - NET_ADMIN
    command: ['sh', '-c', 'ip route del default && ip route add default via 192.168.90.1 && sleep infinity']

  odin:
    image: nicolaka/netshoot
    restart: always
    depends_on:
      - router
    container_name: odin
    networks:
      asgard:
        ipv4_address: 192.168.90.4
    cap_add:
      - NET_ADMIN
    command: [ 'sh', '-c', 'ip route del default && ip route add default via 192.168.90.1 && sleep infinity' ]

  loki:
    image: nicolaka/netshoot
    restart: always
    depends_on:
      - router
    container_name: loki
    networks:
      nilfheim:
        ipv4_address: 192.168.92.3
    cap_add:
      - NET_ADMIN
    command: ['sh', '-c', 'ip route del default && ip route add default via 192.168.92.1 && sleep infinity']

volumes:
  cryton_core_db_data:


networks:
  asgard:
    ipam:
      config:
        - subnet: 192.168.90.0/24
          gateway: 192.168.90.250
  cryton:
    ipam:
      config:
        - subnet: 192.168.91.0/24
          gateway: 192.168.91.250
  nilfheim:
    ipam:
      config:
        - subnet: 192.168.92.0/24
          gateway: 192.168.92.250
  dmz:
    ipam:
      config:
        - subnet: 192.168.50.0/24
          gateway: 192.168.50.250
