version: '3.9'
services:
  wan_router:
    build:
      context: .
      target: wan_router
    restart: always
    container_name: wan_router
    privileged: true
    networks:
      management:
        ipv4_address: 192.168.50.10
      dmz:
        ipv4_address: 192.168.93.1
      cryton:
        ipv4_address: 192.168.90.1
    cap_add:
      - NET_ADMIN

  user_router:
    build:
      context: .
      target: user_router
    restart: always
    container_name: user_router
    privileged: true
    networks:
      management:
        ipv4_address: 192.168.50.11
      user_subnet:
        ipv4_address: 192.168.91.1
    cap_add:
      - NET_ADMIN
    entrypoint: ["sh", "-c", "ip route del default && /sbin/init"]

  server_router:
    build:
      context: .
      target: server_router
    restart: always
    container_name: server_router
    privileged: true
    networks:
      management:
        ipv4_address: 192.168.50.12
      server_subnet:
        ipv4_address: 192.168.92.1
    cap_add:
      - NET_ADMIN
    entrypoint: ["sh", "-c", "ip route del default && /sbin/init"]

  loki:
    image: nicolaka/netshoot
    restart: always
    container_name: loki
    privileged: true
    networks:
      server_subnet:
        ipv4_address: 192.168.92.40
    cap_add:
      - NET_ADMIN
    command: [ 'sh', '-c', 'ip route del default && ip route add default via 192.168.92.1 && sleep infinity' ]

  thor:
    image: nicolaka/netshoot
    restart: always
    container_name: thor
    privileged: true
    networks:
      cryton:
        ipv4_address: 192.168.90.40
    cap_add:
      - NET_ADMIN
    command: [ 'sh', '-c', 'ip route del default && ip route add default via 192.168.90.1 && sleep infinity' ]

  odin:
    image: nicolaka/netshoot
    restart: always
    container_name: odin
    privileged: true
    networks:
      user_subnet:
        ipv4_address: 192.168.91.40
    cap_add:
      - NET_ADMIN
    command: [ 'sh', '-c', 'ip route del default && ip route add default via 192.168.91.1 && sleep infinity' ]

  heimdal:
    image: nicolaka/netshoot
    restart: always
    container_name: heimdal
    privileged: true
    networks:
      dmz:
        ipv4_address: 192.168.93.40
    cap_add:
      - NET_ADMIN
    command: [ 'sh', '-c', 'ip route del default && ip route add default via 192.168.93.1 && sleep infinity' ]

networks:
  cryton:
    ipam:
      config:
        - subnet: 192.168.90.0/24
          gateway: 192.168.90.250
  user_subnet:
    ipam:
      config:
        - subnet: 192.168.91.0/24
          gateway: 192.168.91.250
  server_subnet:
    ipam:
      config:
        - subnet: 192.168.92.0/24
          gateway: 192.168.92.250
  dmz:
    ipam:
      config:
        - subnet: 192.168.93.0/24
          gateway: 192.168.93.250
  management:
    ipam:
      config:
        - subnet: 192.168.50.0/24
          gateway: 192.168.50.250

