version: '3.9'
services:
  aidojo_db:
    restart: always
    image: postgres:15
    container_name: aidojo-db
    env_file:
      - .env
    volumes:
      - ai-dojo-testbed:/var/lib/postgresql/data
    healthcheck:
      test: /usr/bin/pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 20s
      timeout: 10s
      retries: 5

  aidojo_app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: aidojo-app
    container_name: aidojo-app
    depends_on:
      aidojo_db:
        condition: service_healthy
    ports:
      - "0.0.0.0:8000:8000"
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  ai-dojo-testbed:
