[tool.poetry]
name = "docker-testbed"
version = "0.1.0"
description = ""
authors = ["Milan Bohacek <bohacek@ics.muni.cz>", "Jiri Raja <Raja@ics.muni.cz>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
docker = "^6.0.1"
netaddr = "^0.8.0"
randomname = "^0.2.1"
cyst-core = { git = "git@gitlab.ics.muni.cz:cyst/cyst-core.git" }
black = {extras = ["d"], version = "^23.3.0"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
