[tool.poetry]
name = "ai-dojo-docker-testbed"
version = "0.1.0"
description = ""
authors = ["Milan Bohacek <244656@muni.cz>"]
readme = "README.md"
packages = [{include = "ai_dojo_docker_testbed"}]

[tool.poetry.dependencies]
python = "^3.11"
docker = "^6.0.1"
pyyaml = "^6.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
