"""Add depends_on feature

Revision ID: be6dbedc8603
Revises: 66b064e6af24
Create Date: 2024-01-23 15:50:13.801132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'be6dbedc8603'
down_revision: Union[str, None] = '66b064e6af24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('depends_on', sqlalchemy_utils.types.json.JSONType(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('node', 'depends_on')
    # ### end Alembic commands ###
