from netaddr import IPAddress, IPNetwork

PERIMETER_ROUTER = "perimeter_router"
MANAGEMENT_NETWORK_SUBNET = IPNetwork("192.168.50.0/24")
MANAGEMENT_NETWORK_ROUTER_GATEWAY = IPAddress(
    MANAGEMENT_NETWORK_SUBNET.first + 1, MANAGEMENT_NETWORK_SUBNET.version
)

MANAGEMENT_NETWORK_NAME = "management_network"

ROUTER_IMAGE_DEBUG = "nicolaka/netshoot"
IMAGE_BASE = ROUTER_IMAGE_DEBUG
IMAGE_NODE = ROUTER_IMAGE_DEBUG
IMAGE_ROUTER = ROUTER_IMAGE_DEBUG
